import Navbar from '@/components/Navbar'
import './globals.css'
import { Quicksand } from 'next/font/google'
import Footer from '@/components/Footer'
import ProviderState from '@/redux/ProviderState'
import ProviderAuth from '@/components/ProviderAuth'


const inter = Quicksand({ subsets: ['latin'] ,weight:['300','400','500','600','700'] })

export const metadata = {
  title: 'Benz store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <ProviderState>
          <ProviderAuth>
            <Navbar/>
            <div className='pt-14'>
            {children}
            </div>
            <Footer/>
          </ProviderAuth>
        </ProviderState>
      </body>
    </html>
  )
}
